# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 749d63fcc4fae744909ab29bc1e2c487850cb3c5f1b687bfdb3355e9bdefbedbc8b23ae720dc4f76c54f98c66a2134b2242b1467d62390c7e11fc0de3ec2fe97

test:
  secret_key_base: f690f8c600d8b0ec69bb2b48234f3ecc130eb7bb28c6adbd5a404bb56ef656677a964c1677a1e9b0158c6142dcd44520bc2f117783b5f3efc8fd1f7c8324f337

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
